// This file has been autogenerated by configure.py please modify 'config'
// files and run configure.py instead of modifying this file.

#ifndef COMMANDS_H_
#define COMMANDS_H_

#define CMD_PING                                                 0x1
#define CMD_GET                                                  0x2
#define CMD_SET                                                  0x3
#define CMD_SET_LOG                                              0x4
#define CMD_RESET                                                0x5
#define CMD_LOG                                                  0x6
#define CMD_PING_BACK                                            0x7
#define CMD_STATUS_UPDATE                                        0x8

#endif

