// This file has been autogenerated by configure.py please modify 'config'
// files and run configure.py instead of modifying this file.

#ifndef COMMANDS_H_
#define COMMANDS_H_

#define CMD_PING                                 0x01
#define CMD_GET                                  0x02
#define CMD_SET                                  0x03
#define CMD_SET_LOG                              0x04
#define CMD_RESET                                0x05
#define CMD_LOG                                  0x06
#define CMD_PING_BACK                            0x07
#define CMD_STATUS_UPDATE                        0x08
#endif

