// This file has been autogenerated by configure.py please modify 'config'
// files and run configure.py instead of modifying this file.

#ifndef PROTOCOL_H_
#define PROTOCOL_H_

#include <stdint.h>

typedef uint8_t Device_t;
typedef uint8_t Packetsize_t;
typedef uint8_t Command_t;
typedef uint16_t Logmsg_t;
typedef uint8_t Component_t;

#define PACKET_MAX_SIZE                                          30
#define PACKET_START                                             '('
#define PACKET_STOP                                              ')'
#define UART_BAUDRATE                                            9600
#define UART_TIMEOUT                                             1
#define I2C_BAUDRATE                                             9600
#define I2C_TIMEOUT                                              1

#endif

