// This file has been autogenerated by configure.py please modify 'config'
// files and run configure.py instead of modifying this file.

#ifndef COMMUNICATION_LOGMSG_H_
#define COMMUNICATION_LOGMSG_H_

#define ERROR_READ_FAIL_PACKET_SIZE                              0x0001
#define ERROR_READ_FAIL_PACKET_SRC                               0x0002
#define ERROR_READ_FAIL_PACKET_DEST                              0x0003
#define ERROR_READ_FAIL_PACKET_CMD                               0x0004
#define ERROR_READ_FAIL_PACKET_ARGS                              0x0005
#define ERROR_READ_PACKET_SIZE_TOO_BIG                           0x0006
#define ERROR_READ_PACKET_SIZE_TOO_SMALL                         0x0007
#define ERROR_READ_PACKET_MISSING_CMD                            0x0008
#define ERROR_CREATE_PACKET_TOO_BIG                              0x0009
#define ERROR_CREATE_PACKET_INVALID_TYPE                         0x000a
#define INFO_INIT_SUCCESS                                        0x000b
#define WARN_RECEIVED_INVALID_PACKET_HEADER                      0x000c
#define WARN_GARBAGE_DATA                                        0x000d
#define WARN_SIZE_PACKET                                         0x000e

#endif

