
// This file has been autogenerated by configure.py please modify config_*.py
// files and run configure.py instead of modifying this file.

#ifndef COMMUNICATION_H_
#define COMMUNICATION_H_

#include <stdint.h>
#include "array.hpp"
#include "config.h"

typedef uint8_t Address_t;

typedef struct {
	uint8_t dest;
	uint8_t src;
	uint8_t data[14];
} Packet_t;

class Communication {
public:
	Address_t src;

	Communication(Address_t src);
	
	// Get new packets in input queue and return nb of packets in input queue.
	unsigned char fetchPackets(void);

	// return nb of packets in input queue.
	unsigned char available(void);

	// get packet from input queue.
	Packet_t get(void);

	// add packet to output queue. Return nb of packets in output queue
	unsigned char send(const Packet_t* packet);

	// send output queue (may take a while).
	void flush(void);

};

class Rooter : public Communication {
private:
	static unsigned char readNewPacketsFromUART(Queue_t* queue);
	static unsigned char readNewPacketsFromI2C(Queue_t* queue);

public:
	Rooter(Address_t src);

	void flush(void); // return amount of flushed packets?

	unsigned char rootPackets(void);
};

#endif
