
// This file has been autogenerated by configure.py please modify config_*.py
// files and run configure.py instead of modifying this file.

#ifndef COMMUNICATION_H_
#define COMMUNICATION_H_

#include <stdint.h>
#include "array.hpp"
#include "config.h"
#include <string.h>

typedef uint8_t Address_t;

typedef struct {
	Address_t dest, src;
	const char* str;
} Packet_t;

class Communication {
protected:
	StringQueue inputs;

public:
	Address_t address;

	Communication(Address_t src);
	
	// Get new packets in input queue and return nb of byte in input queue.
	virtual unsigned short fetchInputs(void);

	// get packet from input queue.
	Packet_t get(void);

	// send packet and return nb of byte written 
	virtual size_t send(const Packet_t* packet);
};


class Rooter : public Communication {
public:
	Rooter(Address_t src);
	unsigned short fetchInputs(void);
	size_t send(const Packet_t* packet);
};

#endif
