
// This file has been autogenerated by configure.py please modify config_*.py
// files and run configure.py instead of modifying this file.

#ifndef COMMUNICATION_H_
#define COMMUNICATION_H_

#include <stdint.h>
#include "array.hpp"
#include "config.h"

class Communication {
public:
	Address_t src;

	Communication(Address_t src);
	
	// Get new packets in input queue and return nb of packets in input queue.
	unsigned char fetchPackets(void);

	// return nb of packets in input queue.
	unsigned char available(void);

	// get packet from input queue.
	Packet_t get(void);

	// add packet to output queue. Return nb of packets in output queue
	unsigned char send(Address_t dest, const char* msg);

	// send output queue (may take a while).
	void flush(void);

};

#endif
