
// This file has been autogenerated by configure.py please modify config_*.py
// files and run configure.py instead of modifying this file.

#ifndef COMMUNICATION_H_
#define COMMUNICATION_H_

typedef char Address_t;
typedef enum : Address_t {
	COM_ADDRESS_ROOTER     = 0x00,
	COM_ADDRESS_COMPUTER   = 0x01,
	COM_ADDRESS_CLOCK      = 0x02,
	COM_ADDRESS_PUZZLE1    = 0x03,
	COM_ADDRESS_PUZZLE2    = 0x04
} com_Address_e;

typedef struct {
	unsigned char i, n;

} Fragment_t;

typedef struct {
	Address_t dest, src;
	
} pute;

#endif
