// This file has been autogenerated by configure.py please modify 'config'
// files and run configure.py instead of modifying this file.

#ifndef DEVICE_H_
#define DEVICE_H_

#define DEVICE                                                   0x4
#define COMPUTER                                                 0x2
#define HUB                                                      0x6

#define LED_BUILTIN                                              0x01

#endif

