// This file has been autogenerated by configure.py please modify 'config'
// files and run configure.py instead of modifying this file.

#ifndef LOGMSG_H_
#define LOGMSG_H_

#define INFO_INIT_SUCCESS                                        0x0001

#endif

