// This file has been autogenerated by configure.py please modify 'config'
// files and run configure.py instead of modifying this file.

#ifndef DEBUG_LOGMSG_H_
#define DEBUG_LOGMSG_H_

#define WARN_AAA                                 0x000f
#define WARN_BBB                                 0x0010
#define WARN_CCC                                 0x0011
#endif

