
// This file has been autogenerated by configure.py please modify config_*.py
// files and run configure.py instead of modifying this file.

#ifndef INFO_H_
#define INFO_H_

#define DEVICE_NAME "clock"
#define DEVICE_ID 1

#endif
