// This file has been autogenerated by configure.py please modify 'config'
// files and run configure.py instead of modifying this file.

#ifndef DEVICE_H_
#define DEVICE_H_

#define DEVICE                                   0x01
#define COMPUTER                                 0x01
#define HUB                                      0x03
#endif

