ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
AVRDUDE_CONF = /etc/avrdude.conf
USER_LIB_PATH := $(realpath ../includes) 

CXXSRC = main.cpp rooting.cpp  
CPPFLAGS = -I../includes

include ${ARDUINO_DIR}/Arduino.mk

